name: rag
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - numpy
  - faiss-cpu
  - uvicorn
  - fastapi
  - pydantic
  - pip:
      - langchain==0.0.350
      - langchain-community==0.0.20
      - openai
      - pypdf
      - python-dotenv
      - mlflow